### ISSUE TITLE
[Fix] 삭제된 경로에서 pwd 고장나는 부분 처리

### ISSUE THREAD

**Issue by nheo9143** [tamagoyakii/minishell#137]
### ISSUE
 * Type: `fix`
 * Detail: 삭제된 경로에서 pwd 고장나는 부분 처리

 ### TODO
- [ ]  삭제된 경로에서 pwd 고장나는 부분 처리
<img width="391" alt="image" src="https://user-images.githubusercontent.com/90181905/194707441-a5f50f8e-8499-407e-856c-ea3c698ec68a.png">

<img width="499" alt="image" src="https://user-images.githubusercontent.com/90181905/194707455-c46f7d3d-9c10-4bfe-b3cd-1ed13661c536.png">

-- 문제 여지가 있을것같은 부분 --
<img width="720" alt="image" src="https://user-images.githubusercontent.com/90181905/194707523-89c2b09f-00e4-4167-95ec-5f296def60fa.png">

**Comment by nheo9143** [comment]
확인해보니 bash에서도 쉘속에서 쉘키면 똑같이 되네요..! 처리 안해도 될듯합니다!!

**Comment by tamagoyakii** [comment]
주말까지 열심히신 남준님. .... 굿!
