### ISSUE TITLE
[Feat] builtin 함수 작성

### ISSUE THREAD

**Issue by nheo9143** [tamagoyakii/minishell#30]
### ISSUE
 * Type: `feature`
 * Detail: builtin 함수 작성
 
 ### TODO
- [x]  ft_echo 구현
- [x]  ft_exit 구현
- [x]  ft_cd 구현
- [x]  ft_pwd 구현
- [x]  ft_env 구현
- [x]  ft_export 구현
- [x]  ft_unset 구현

**Comment by pearpearB** [comment]
#26 #35 #37
