### ISSUE TITLE
[Fix] 리다이렉트, 파이프 파싱 오류

### ISSUE THREAD

**Issue by nheo9143** [tamagoyakii/minishell#55]
### ISSUE
 * Type:`fix`
 * Detail: 리다이렉트, 파이프 파싱 오류
 
 ### TODO
- [ ]  파이프 + 리다렉트 들어오면 값이 이상하게 들어오는 문제 처리
- [x]  맨 처음 리다렉트 인풋("<") 들어오면 처리 안되는 부분 해결 (segfault)

파이프 + 리다렉트 들어오면 값이 이상하게 들어옴
증상 : 파이프 이전에 리다이렉트 들어오면 세그폴트
	파이프 뒤에 리다이렉트 들어오면 맨 처음 argv에만 들어가있음..ㅠㅠ
	

	expect :
		argv : [cmd : ~~],
				[in : NULL],
				[out : NULL],
				[hdoc : NULL]
				[next : 
					argv : [cmd : ~~],
							[in : “test.txt”],
							[out : NULL],
							[hdoc : NULL]
							[next : NULL]

	current :
		argv : [cmd : ~~],
				[in : “test.txt”],
				[out : NULL],
				[hdoc : NULL]
				[next : 
					argv : [cmd : ~~],
							[in : NULL],
							[out : NULL],
							[hdoc : NULL]
							[next : NULL]

**Comment by tamagoyakii** [comment]
죄송함다... 열심히 고쳐놓겠습니다.....
